apiVersion: v1
kind: Service
metadata:
  name: controller-manager-webhook
  labels:
    app.kubernetes.io/name: gitship
    app.kubernetes.io/component: webhook
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: gitship
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: webhook
  type: ClusterIP
