kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitship-registry.gitship-system.svc.cluster.local:5000"]
    endpoint = ["http://gitship-registry.gitship-system.svc.cluster.local:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."gitship-registry.gitship-system.svc.cluster.local:5000".tls]
    insecure_skip_verify = true
