apiVersion: ci.gitship.io/v1alpha1
kind: RepoWatcher
metadata:
  labels:
    app.kubernetes.io/name: gitship
    app.kubernetes.io/managed-by: kustomize
  name: repowatcher-sample
spec:
  repoUrl: "https://github.com/example/repo"
