apiVersion: gitship.io.gitship.io/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: gitship
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  githubUsername: "sampleuser"
