apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitship.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gitship.name" . }}-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitship.name" . }}-controller
  template:
    metadata:
      labels:
        app: {{ include "gitship.name" . }}-controller
    spec:
      serviceAccountName: {{ include "gitship.fullname" . }}-controller-manager
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: REGISTRY_PUSH_URL
              value: {{ .Values.controller.config.registryPushUrl | quote }}
            - name: REGISTRY_PULL_URL
              value: {{ .Values.controller.config.registryPullUrl | quote }}
            - name: SYSTEM_NAMESPACE
              value: {{ .Values.controller.config.systemNamespace | quote }}
            - name: INGRESS_CLASS_NAME
              value: {{ .Values.controller.config.ingressClassName | quote }}
            - name: DEFAULT_STORAGE_CLASS
              value: {{ .Values.controller.config.defaultStorageClass | quote }}
            - name: QUOTA_CPU
              value: {{ .Values.quotas.limits.cpu | quote }}
            - name: QUOTA_RAM
              value: {{ .Values.quotas.limits.memory | quote }}
            - name: QUOTA_PODS
              value: {{ .Values.quotas.pods | quote }}
            - name: QUOTA_STORAGE
              value: {{ .Values.quotas.storage | quote }}
            - name: IMAGE_GIT
              value: {{ .Values.controller.config.images.git | quote }}
            - name: IMAGE_KANIKO
              value: {{ .Values.controller.config.images.kaniko | quote }}
            {{- if .Values.github.webhookSecret }}
            - name: GITHUB_WEBHOOK_SECRET
              value: {{ .Values.github.webhookSecret | quote }}
            {{- end }}
          ports:
            - containerPort: 3001
              name: webhook
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitship.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitship.fullname" . }}-controller-manager-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gitship.name" . }}-controller
spec:
  selector:
    app: {{ include "gitship.name" . }}-controller
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: webhook
  type: ClusterIP
